- CHANGELOG.md
- src/DynamicMvvm.Abstractions/Command/IDynamicCommand.md
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
- src/DynamicMvvm/Command/Strategies/LoggerCommandStrategy.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.cs
- Feature
- `ViewModelBase` uses the `ServiceProvider` to get its logger.
- The `ILogger` parameters of the `IDynamicCommandStrategy.WithLogs()` is not optional.
- `ViewModelBase` uses `DynamicMvvmConfiguration.LoggerFactory` to get its logger.
- The `ILogger` parameters of the `IDynamicCommandStrategy.WithLogs()` is optional.
> Use DynamicMvvmConfiguration.LoggerFactory everywhere to get logger 

- src/DynamicMvvm.Tests/Integration/IntegrationTests.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Disposable.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Errors.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.PropertyChanged.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.View.cs
- Bug fix
ViewModelBase can still be used once it's been disposed.
ViewModelBase now throws ObjectDisposedException when we try to mutate it after it's been disposed.
> fix: ViewModelBase now throws when used after having been disposed.

- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseChildrenTests.cs
Feature
Currently, when we try to attach again a child (with the same name) on a parent ViewModel, it will throws an exception. 
Now, if you use the extension method AttachOrReplaceChild, it will detach the previous instance (and disposed it) and attach the new instance to the parent ViewModel.
> Implemented new IViewModelExtension AttachOrReplaceChild

- build/gitversion.yml
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Commands.cs
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.cs
- src/DynamicMvvm.Abstractions/ViewModel/IViewModelView.cs
- src/DynamicMvvm.Tests/Helpers/TestViewModelView.cs
- src/DynamicMvvm.Tests/Integration/IntegrationTests.cs
- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseDisposableTests.cs
- src/DynamicMvvm.Uno/ViewModel/ViewModelView.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Disposable.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Errors.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.PropertyChanged.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.View.cs
- Bug fix
- Feature 
Trying to read a disposed `IViewModel`'s property written using `this.Get` throws an `ObjectDisposedException`.
Reading a property from a disposed `IViewModel` yields a default value instead of throwing an `ObjectDisposedException`.
A default value is also returned when using the `GetCommandFromXXX` and `GetChild` extensions.
> fix: Improve ViewModelBase behavior when disposed

- src/DynamicMvvm/ViewModel/ViewModelBase.Errors.cs
GitHub Issue: #27
Bug fix
`ViewModelBase.HasErrors` checks if the dictionary has anything in it.
`ViewModelBase.HasErrors` checks if the dictionary contains errors for any property name.
> fix: properly check if there are errors with ViewModelBase.HasErrors

- build/gitversion.yml
- src/DynamicMvvm.Abstractions/ViewModel/IViewModelView.cs
- src/DynamicMvvm.Tests/Helpers/TestViewModelView.cs
- src/DynamicMvvm.Uno/ViewModel/ViewModelView.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Disposable.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.PropertyChanged.cs
- Bug fix
If a child ViewModel is disposed, it's parent's `IViewModelView` is disposed as well, breaking the dispatcher reference.
- `IViewModel` no longer implements `IDisposable`.
- `ViewModelBase` now exposes a public `CancellationToken`.
> fix: Fix ViewModelView being disposed when it shouldn't

- src/DynamicMvvm.Tests/Command/Strategies/ActionCommandStrategyTests.cs
- src/DynamicMvvm.Tests/Command/Strategies/TaskCommandStrategyTests.cs
- src/DynamicMvvm/Command/Strategies/ActionCommandStrategy.T.cs
- src/DynamicMvvm/Command/Strategies/ActionCommandStrategy.cs
- src/DynamicMvvm/Command/Strategies/TaskCommandStrategy.T.cs
- src/DynamicMvvm/Command/Strategies/TaskCommandStrategy.cs
- Bug fix 
- There are sometimes null reference exceptions getting thrown from the canExecute of `ActionCommandStrategy` or `TaskCommandStrategy`.
- Note however that those `canExecute` funcs are not actually used and are not as good as `CanExecuteCommandStrategy`.
- It is no longer possible to instanciate `ActionCommandStrategy` or `TaskCommandStrategy` with a `canExecute` parameter.
- `CanExecuteCommandStrategy` is (and always has been) the proper way of specifying a `CanExecute` func.
> fix: Remove canExecute funcs from ActionCommandStrategy and TaskCommandStrategy

- src/DynamicMvvm.Reactive/Property/IDynamicPropertyExtensions.cs
- src/DynamicMvvm.Tests/Reactive/DynamicPropertyExtensionsTests.cs
- Bug fix
When using `GetAndObserve`, the value from `StartWith` can be the wrong one based on how you use the observable.
It works fine if you subscribe to the observable once.
However, if you subscribe to the same observable again, the `StartWith` will cause the observable sequence to play the value captured when the observable was created, not the current value of the property.
The new implementation of `GetAndObserve` doesn't use `StartWith`. It uses `Observable.Create` to make sure the first value of the sequence is the current value of the property, no matter the situation.
> fix: Fix IDynamicProperty.GetAndObserve extension

- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseDisposableTests.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Disposable.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.cs
- Bug fix
We get an ObjectDisposedException when accessing `ViewModelBase.CancellationToken` after disposing the view model.
We get an cancelled token when accessing `ViewModelBase.CancellationToken` after disposing the view model.
> fix: Prevent object disposed exception when reading ViewModelBase.CancellationToken

- CHANGELOG.md
- build/azure-pipelines.yml
- build/gitversion.yml
- src/DynamicMvvm.Tests/DynamicMvvm.Tests.csproj
- src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj
GitHub Issue: N/A
Remove support for Android 10
Update UWP target to 19041 and net framework to 4.7.2
Build with VS2022
Support for Android 12
Feature
Build or CI related changes
Documentation content changes 
No support for Android 12
Support for Android 12
Since all new projects will need to target Android 12, it is not needed to target Android 10 anymore
> target Android 12 and use VS2022 to compile

- src/DynamicMvvm.Tests/Property/ValueChangedOnBackgroundTaskDynamicPropertyTests.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicProperty.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFactory.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromObservable.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromTask.cs
- Feature
- Add new implementations of `IDynamicProperty`.
- `ValueChangedOnBackgroundTaskDynamicProperty` is an implementation that ensures that the `ValueChanged` event is raised on a background task (to avoid executing business logic on the `CoreDispatcher`).
> feat: Add new dynamic property implementations

- src/DynamicMvvm.Abstractions/AssemblyInfo.cs
- src/DynamicMvvm.Abstractions/Deactivation/IDeactivatable.cs
- src/DynamicMvvm.Abstractions/Deactivation/IDeactivatableViewModel.cs
- src/DynamicMvvm.Reactive/Deactivation/DeactivatableObservable.cs
- src/DynamicMvvm.Reactive/Deactivation/IObservable.Extensions.cs
- src/DynamicMvvm.Tests/Integration/DeactivationIntegrationTests.cs
- src/DynamicMvvm.Tests/Reactive/DeactivatableObservableTests.cs
- src/DynamicMvvm.Tests/ViewModel/DeactivatableViewModelBaseTests.cs
- src/DynamicMvvm/Deactivation/DeactivatableDynamicPropertyFromObservable.cs
- src/DynamicMvvm/Deactivation/DeactivatableViewModelBase.cs
- src/DynamicMvvm/Deactivation/IDeactivatableViewModel.Extensions.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.cs
- Feature 
Introduce new interfaces and some implementations for performance optimization.
Implement `IDeactivatable` on a reactive object (like a ViewModel, a dynamic property or an observable) to temporarily deactivate it to prevent updates that would cause unnecessary processing.
Example: if a page ViewModel exists in the navigation stack, but isn't the top-most one, it is still raising events like PropertyChanged to update data bindings, but no one sees the view bound to that data.
- Add `IDeactivatable` and `IDeactivatableViewModel`
- Add `DeactivatableObservable<T>`, an `IObservable` wrapper that allows _pausing_ the observable subscription.
- Add `DeactivatableDynamicPropertyFromObservable<T>`, a dynamic property from observable that allows _pausing_ the observable …
> feat: Add Deactivation namespace

- Directory.Build.targets
- Build or CI related changes 
The [SourceLink workaround](https://github.com/clairernovotny/DeterministicBuilds#work-around-for-net-sdk-prior-31300) is not there.
The [SourceLink workaround](https://github.com/clairernovotny/DeterministicBuilds#work-around-for-net-sdk-prior-31300) is there.
> build: Add SourceLink workaround for AssemblyInfo

- src/DynamicMvvm.Tests/Command/Strategies/RaiseCanExecuteOnDispatcherCommandStrategyTests.cs
- src/DynamicMvvm/Command/DynamicCommandBuilderFactory.cs
- src/DynamicMvvm/Command/Strategies/RaiseCanExecuteOnDispatcherCommandStrategy.cs
- Feature
Add `RaiseCanExecuteOnDispatcherCommandStrategy`, a strategy that ensures that `CanExecuteChanged` is raised on the dispatcher when possible.
> feat: Add RaiseCanExecuteOnDispatcherCommandStrategy + tests

- src/DynamicMvvm/ViewModel/ViewModelBase.PropertyChanged.cs
- Feature 
When a child ViewModel is not attached to its parent using `AttachChild`, `GetChild` or `AttachOrReplaceChild`, the UI-thread-related exception doesn't hint the missing relationship between child and parent ViewModels.
The UI-thread-related exception is followed by a helpful error log that hints the solution.
> feat: Add helpful log message when PropertyChanged fails.

- .github/PULL_REQUEST_TEMPLATE.md
- build/azure-pipelines.yml
Feature branches automatically release packages.
Feature branches don't automatically release packages.
> ci: Don't automatically run the pipeline on feature branches.

- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseChildrenTests.cs
... Let Dispose do it at the right time.
`DetachChild` sets the `IViewModel.Dispatcher` to null. This can lead to incorrect behaviors when the view is still subscribed to `PropertyChanged`.
`DetachChild` no longer sets `IViewModel.Dispatcher` to null.
> fix: Don't set the Dispatcher to null when detaching child VMs.

- src/DynamicMvvm.Tests/Property/DynamicPropertyFactoryTests.cs
- src/DynamicMvvm.Tests/Property/DynamicPropertyTests.T.cs
- src/DynamicMvvm.Tests/Property/DynamicPropertyTests.cs
- src/DynamicMvvm/Property/DynamicProperty.T.cs
- src/DynamicMvvm/Property/DynamicProperty.cs
- src/DynamicMvvm/Property/DynamicPropertyFactory.cs
- src/DynamicMvvm/Property/DynamicPropertyFromObservable.cs
- src/DynamicMvvm/Property/DynamicPropertyFromTask.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicProperty.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFactory.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromObservable.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromTask.cs
By default, when trying to set a disposed property, it will throw a `ObjectDisposedException`.
We provide the option to configure `IDynamicProperty` implementations to prevent exceptions from being thrown when attempting to set a property that has been disposed.
> Introducing ThrowOnDisposed on IDynamicPropety implementations

- src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
- src/DynamicMvvm.Uno.WinUI/winappsdk-workaround.targets
Currently when upgrading a project to Uno 5+ the following message is displayed when using this package:
Workaround implemented avoids including Uno.Toolkit.UI XBFs in the PRI file
Currently a WIP as the investigation continues to locate all the packages that cause this exception to be thrown
> fix: implemented workaround for Uno.Toolkit.UI error

- build/stage-build.yml
[#294918](https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/294918)
Apps which compile using .NET SDK 7 encounter build errors when using Chinook.DynamicMvvm
Apps which compile using .NET SDK 7.0.102 build correctly
.NET SDK 7.0.100 has [issues](https://github.com/coverlet-coverage/coverlet/issues/1391) …
> fix: Use uno-check to compile with .net sdk 7.0.102

- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseChildrenTests.cs
GitHub Issue: #87
- `DetachChild` throws exceptions when called with a disposed child.
- `DetachChild` doesn't throw exceptions when called with a disposed child.
> fix: Prevent exceptions from being thrown when detaching a disposed child

- src/DynamicMvvm.Tests/Integration/DeactivationIntegrationTests.cs
- src/DynamicMvvm/Deactivation/IDeactivatableViewModel.Extensions.cs
GitHub Issue: solves #89
- Add overload of `GetFromDeactivatableObservable` that uses a `Func<IObservable<T>>` to allow lazy evaluation of the observable sequence to allow fewer memory allocations.
> feat: Add overload of GetFromDeactivatableObservable that uses a Func

- BREAKING_CHANGES.md
- src/DynamicMvvm.Tests/Property/DynamicPropertyFactoryTests.cs
- src/DynamicMvvm.Tests/Property/DynamicPropertyTests.T.cs
- src/DynamicMvvm.Tests/Property/DynamicPropertyTests.cs
- src/DynamicMvvm/LoggerMessages.cs
- src/DynamicMvvm/Property/DynamicProperty.T.cs
- src/DynamicMvvm/Property/DynamicProperty.cs
- src/DynamicMvvm/Property/DynamicPropertyFactory.cs
- src/DynamicMvvm/Property/DynamicPropertyFromObservable.cs
- src/DynamicMvvm/Property/DynamicPropertyFromTask.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicProperty.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFactory.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromObservable.cs
- src/DynamicMvvm/Property/ValueChangedOnBackgroundTask/ValueChangedOnBackgroundTaskDynamicPropertyFromTask.cs
GitHub Issue:
Fixes #90 
- Setting the `Value` property of a `DynamicProperty` while it is disposed throws an `ObjectDisposedException`.
- Setting the `Value` property of a `DynamicProperty` while it is disposed logs a debug message.
- All overloads using a `throwOnDisposed` parameters are marked as obsolete.
> fix: DynamicProperties no longer throw ObjectDisposedExceptions

- src/DynamicMvvm.Tests/ViewModel/ViewModelBaseErrorsTests.cs
- src/DynamicMvvm/ViewModel/ViewModelBase.Errors.cs
- The internal `_errors` dictionary for the `INotifyDataErrorInfo` aspect of `ViewModelBase` is always instantiated, even if the `INotifyDataErrorInfo` features aren't used for a ViewModel.
- The `_errors` dictionary is a `ConcurrentDictionary`.
| Method                              | Mean      | Allocated |
|------------------------------------ |----------:|----------:|
| CreateViewModel                     |  2.057 μs |    1760 B |
| CreateViewModel_WithExplicitName    |  2.077 μs |    1760 B |
- The `_errors` field is now a `Dictionary`. We weren't using any features specific to `ConcurrentDictionary`.
- The `_errors` field is now lazy-initialized. It stays `null` as long a we don't call `SetErrors`.
| Method                              | Mean      | Allocated | …
> perf: Make ViewModelBase's internal errors dictionary lazy initialized

- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
| Method                           | Mean        | Gen0   | Gen1   | Allocated |
|--------------------------------- |------------:|-------:|-------:|----------:|
| GetFromValue_Unresolved          |   427.69 ns | 0.0405 | 0.0401 |     256 B |
| GetFromObservable_Unresolved     |   544.88 ns | 0.0477 | 0.0467 |     304 B |
| GetFromValue_Resolved            |    46.09 ns | 0.0191 |      - |     120 B |
| GetFromObservable_Resolved       |    52.72 ns | 0.0204 |      - |     128 B |
- Faster reads and less memory allocations.
- No allocations when reading resolved properties.
| Method                           | Mean        | Gen0   | Gen1   | Allocated |
|--------------------------------- |------------:|-------:|-------:|----------:|
| GetFromValue_Unresolved          | …
> perf: Improve performance when reading dynamic properties.

- README.md
- src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
- src/DynamicMvvm.Tests/Integration/IntegrationTests.cs
Fixes #99 
- Add an overload of `GetFromObservable` that uses a `Func<IObservable<T>>` to avoid potential wasteful materializations of observable chains.
- Only code in the Benchmarks project was changed.
> feat: Add an overload of GetFromObservable that uses a func
