nventive/Chinook.DynamicMvvm

build/azure-pipelines.yml
build/stage-release.yml

- Build or CI related changes
Fix the release process

Fix the release process

---

CHANGELOG.md
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

Update Android Target to 10.0 supported since Uno 2.3

Update Android target to 10.0

---

README.md
src/DynamicMvvm.Abstractions/Command/IDynamicCommand.md

- Documentation content changes
Update documentation around commands.

Update command documentation

---

src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

Other, please describe:
Update to Uno.UI 3.1.6
Chinook.DynamicMvvm references an older version of Uno.UI : 2.4.0. This makes it harder for projects to use this library if they have updated their version of Uno.UI.
Chinook.DynamicMvvm references Uno.UI 3.1.6

Update to Uno.UI 3.1.6

---

src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

Other, please describe:
Update Uno.UI version
Using version 3.1.6 of Uno.UI
Using version 3.1.0-beta.84 of Uno.UI

chore: Update to Uno.UI version 3.1.0-beta.84

---

CHANGELOG.md
build/azure-pipelines.yml
build/gitversion.yml
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

Feature : Adds support for Android 11
No support for Android 11.
Support for Android 11.
~~- [ ] Automated Unit / Integration tests for the changes have been added/updated~~

feat: Adds support for Android 11

---

src/DynamicMvvm.Abstractions/Command/IDynamicCommandBuilderFactory.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Commands.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Services.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModelView.cs

- Documentation content changes
- Align some of the documentation with the docs.microsoft format

Improve XML documentation

---

src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

Bumped Uno.UI ref
- Beta 3.1.0
- Stable 3.6.6

chore: bumped uno.ui

---

src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

This reverts commit bb4bdc94885b728e02ee83b6c959cd6ab635ba6d.

Revert "chore: bumped uno.ui"

---

README.md
src/DynamicMvvm.Abstractions/Command/IDynamicCommand.md
src/DynamicMvvm.Abstractions/Command/IDynamicCommandBuilder.Extensions.cs
src/DynamicMvvm.Abstractions/Command/IDynamicCommandBuilder.cs
src/DynamicMvvm.Abstractions/Command/IDynamicCommandStrategy.cs
src/DynamicMvvm.Abstractions/Property/IDynamicProperty.Extensions.cs
src/DynamicMvvm.Abstractions/Property/IDynamicProperty.cs
src/DynamicMvvm.Abstractions/Property/IDynamicProperty.md
src/DynamicMvvm.Abstractions/Property/IDynamicPropertyFactory.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Children.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Commands.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Properties.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.Extensions.Services.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.md
src/DynamicMvvm.FluentValidation/IViewModel.Extensions.Validation.cs
src/DynamicMvvm.Reactive/Command/IDynamicCommandExtensions.cs
src/DynamicMvvm.Reactive/Property/IDynamicPropertyExtensions.cs

Documentation content changes
Documentation with some errors
Fixing documentation errors

Update documentation and xml comments

---

src/DynamicMvvm/Property/DynamicPropertyFactory.cs
src/DynamicMvvm/Property/DynamicPropertyFromObservable.cs
src/DynamicMvvm/ViewModel/ViewModelBase.PropertyChanged.cs

- Feature 
- Make members virtual and public to ease extensibility.

feat: Make some members virtual to ease extensibility

---

CHANGELOG.md
build/azure-pipelines.yml
build/gitversion.yml
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj

- Feature 
DynamicMvvm.Uno Targets Uno.UI 3.1.X.
DynamicMvvm.Uno Targets Uno.UI 4.0.7.

chore: bump to uno 4

---

src/DynamicMvvm.FluentValidation/DynamicMvvm.FluentValidation.csproj

Update FluentValidation Minimum version

---

src/DynamicMvvm.Abstractions/DynamicMvvm.Abstractions.csproj
src/DynamicMvvm.FluentValidation/DynamicMvvm.FluentValidation.csproj
src/DynamicMvvm.Reactive/DynamicMvvm.Reactive.csproj
src/DynamicMvvm.Tests/DynamicMvvm.Tests.csproj
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj
src/DynamicMvvm/DynamicMvvm.csproj

- Feature
This PR includes the changes needed to support SourceLink.

feat: add SourceLink to Chinook.DynamicMvvm

---

build/stage-build.yml

- Build or CI related changes
`ContinuousIntegrationBuild` is not set to true.
`ContinuousIntegrationBuild` is set to true.

build: Add ContinuousIntegrationBuild flag

---

src/DynamicMvvm.Abstractions/ViewModel/IViewModelViewFactory.cs
src/DynamicMvvm.Uno/ViewModel/ViewModelViewFactory.cs

- Feature 
- Add IViewModelViewFactory and its implementation.

feat: Add IViewModelViewFactory and its implementation.

---

src/DynamicMvvm.Uno/PreserveAttribute.cs
src/DynamicMvvm.Uno/ViewModel/ViewModelViewFactory.cs

- Bug fix
`ViewModelViewFactory`  can be linked out.
`ViewModelViewFactory`  cannot be linked out.

fix: Prevent ViewModelViewFactory from being linked out.

---

README.md

- Documentation content changes 
Revamp the documentation.

doc: Improve documentation.

---

CHANGELOG.md
build/gitversion.yml
src/DynamicMvvm.Abstractions/Command/DecoratorCommandStrategy.cs
src/DynamicMvvm.Abstractions/Command/IDynamicCommand.md
src/DynamicMvvm.Abstractions/Command/IDynamicCommandBuilder.Extensions.cs
src/DynamicMvvm.Abstractions/Command/IDynamicCommandBuilder.cs
src/DynamicMvvm.Abstractions/ViewModel/IViewModel.md
src/DynamicMvvm.Tests/Command/DynamicCommandBuilderFactoryTests.cs
src/DynamicMvvm/Command/DynamicCommandBuilder.cs
src/DynamicMvvm/Command/Strategies/BackgroundCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/CanExecuteCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/CancelPreviousCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/DisableWhileExecutingCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/ErrorHandlerCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/LockCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/LoggerCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/RaiseCanExecuteOnDispatcherCommandStrategy.cs
src/DynamicMvvm/Command/Strategies/SkipWhileExecutingCommandStrategy.cs

- Feature
- Rename `DecoratorCommandStrategy` to `DelegatingCommandStrategy`.

feat!: Rename DecoratorCommandStrategy to DelegatingCommandStrategy.

---

build/stage-build.yml
src/DynamicMvvm.Tests/DynamicMvvm.Tests.csproj

- Build or CI related changes
Code coverage report is not available in build pipeline.
Code coverage report is available in build pipeline.

build: Add code coverage report in pipeline.

---

.github/workflows/conventional-commits.yml

- Build or CI related changes 
- Add conventional commits github workflow

ci: Add conventional commits github workflow

---

build/azure-pipelines.yml
build/stage-build.yml
nuget.config

- Build or CI related changes
- Update image to VS 17.2.5

ci: Update image to VS 17.2.5

---

build/azure-pipelines.yml

- Add back removed NUGET_VERSION variable.

ci: Fix release variable.

---

.github/workflows/conventional-commits.yml

Update commitsar config to target latest version.

ci: Update commitsar.

---

src/DynamicMvvm.Abstractions/DynamicMvvm.Abstractions.csproj
src/DynamicMvvm.CollectionTracking/DynamicMvvm.CollectionTracking.csproj
src/DynamicMvvm.FluentValidation/DynamicMvvm.FluentValidation.csproj
src/DynamicMvvm.Reactive/DynamicMvvm.Reactive.csproj
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj
src/DynamicMvvm/DynamicMvvm.csproj

- Improve package metadata.
- Cause major version bump so that this marks v1.0.0 🚀.

ci!: Improve package metadata for v1.0.0.

---

build/gitversion.yml

Committing using the "ci" conventional commit type increments the version number.
Committing using the "ci" conventional commit type **does not** increment the version number.

ci: Prevent version bumps when using the "ci" conventional commit type.

---

.mergify.yml
CONTRIBUTING.md
build/gitversion.yml
build/stage-build.yml
src/DynamicMvvm.Abstractions/DynamicMvvm.Abstractions.csproj
src/DynamicMvvm.CollectionTracking/DynamicMvvm.CollectionTracking.csproj
src/DynamicMvvm.FluentValidation/DynamicMvvm.FluentValidation.csproj
src/DynamicMvvm.Reactive/DynamicMvvm.Reactive.csproj
src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
src/DynamicMvvm.Uno/DynamicMvvm.Uno.csproj
src/DynamicMvvm/DynamicMvvm.csproj

chore: cleanup project

---

README.md

- Update readme (add shields, add _more like this_ section, small improvements).

docs: Update readme to and shields and some more details.

---

BREAKING_CHANGES.md
build/stage-build.yml
src/DynamicMvvm.Abstractions/DynamicMvvm.Abstractions.csproj
src/DynamicMvvm.Benchmarks/DynamicMvvm.Benchmarks.csproj
src/DynamicMvvm.CollectionTracking/DynamicMvvm.CollectionTracking.csproj
src/DynamicMvvm.FluentValidation/DynamicMvvm.FluentValidation.csproj
src/DynamicMvvm.Reactive/DynamicMvvm.Reactive.csproj
src/DynamicMvvm.Tests/DynamicMvvm.Tests.csproj
src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj
src/DynamicMvvm.Uno.WinUI/winappsdk-workaround.targets
src/DynamicMvvm/DynamicMvvm.csproj

Projects in the solution target .NET 6-7 and C# 10-11.
Projects in the solution target .NET 8 and C# 12.
- Only code in the Benchmarks project was changed.

chore!: Dotnet 8

---

src/DynamicMvvm.Uno.WinUI/DynamicMvvm.Uno.WinUI.csproj

Uno.SourceGenerationTasks is referenced.
Uno.SourceGenerationTasks is not referenced.
- Only code in the Benchmarks project was changed.

chore: Remove reference to Uno.SourceGenerationTasks.
